### ISSUE TITLE
CI Broken?

### ISSUE THREAD

**Issue by jberkhahn** [operator-framework/operator-manifest-tools#33]
Hey,

So Operator SDK has been doing some minor work in this repo recently, and it seems the CI is now broken, and the CI seems dependent on some containerbuildsystem stuff we don't have access to. 

I think @zach-source has access to these resources. Are you still available to help maintain this repo? We at SDK are thinking of moving the pieces we use inline to the sdk repo and archiving this repository, what are your thoughts on that?

**Comment by zach-source** [comment]
I'll take a look at the CI and the PR.

**Comment by zach-source** [comment]
I took a peek the other day. The image still appear to be available but something else it going wrong. I checked a past git commit to see if it was an introduced change but it failed as well. No one has really touched the integration tests since me so I'm not entirely sure what is going wrong. I'd like to get the integration tests working again but haven't had time to get into it. I'll attempt to grab a few cycles this weekend. The integration tests are inherited from the python repository and I only modified them enough to work with the golang version; so my knowledge is a little lax.

**Comment by jberkhahn** [comment]
cool, thanks. It looks to me like the test runner was failing to inspect the image for some reason.

**Comment by zach-source** [comment]
I've just disabled it for now; from trying to pull the images I couldn't see any issues with the images themselves. Until the proper time can be put into fixing them the overall functionality hasn't changed so little risk in drift. We'll need to address a fix sometime in the future.

**Comment by zach-source** [comment]
Skopeo exec was missing from the build image (used to be included automatically). Changed CLI default to crane; job is now enabled and passing.
